rd /s /q Display.Optimus
rd /s /q Display.NView
rd /s /q Display.Update
rd /s /q GFExperience
rd /s /q GFExperience.NvStreamSrv
rd /s /q GfExperienceService
rd /s /q LEDVisualizer
rd /s /q Miracast.VirtualAudio
rd /s /q MS.NET
rd /s /q MSVCRT
rd /s /q Network.Service
rd /s /q NV3DVision
rd /s /q NV3DVisionUSB.Driver
rd /s /q NvCamera
rd /s /q NvVAD
rd /s /q ShadowPlay
rd /s /q ShieldWirelessController
rd /s /q Update.Core
rd /s /q nodejs
rd /s /q NvBackend
rd /s /q NvContainer
rd /s /q NvTelemetry
rd /s /q NvvHCI